# Generated by Django 5.2.2 on 2025-06-24 06:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_department_leavetype_employee_profile_photo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payslip',
            old_name='deductions',
            new_name='basic_salary',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='detail',
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='gross_pay',
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='pay_period',
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='summary',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='details',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='employee_photos/'),
        ),
        migrations.AddField(
            model_name='payslip',
            name='days_worked',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payslip',
            name='employee_id_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='payslip',
            name='hdmf',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payslip',
            name='late_deduction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payslip',
            name='period_from',
            field=models.DateField(default=datetime.date(2025, 6, 24)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payslip',
            name='period_to',
            field=models.DateField(default=datetime.date(2025, 6, 24)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payslip',
            name='phic',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payslip',
            name='regular_holidays',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payslip',
            name='sss',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payslip',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payslip',
            name='total_deductions',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(max_length=100),
        ),
    ]
