# Generated by Django 5.2.4 on 2025-08-22 05:08

from django.db import migrations
from ..roles import setup_roles_and_permissions


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_late_deduction_payslip_daily_rate_and_more'),
    ]

    operations = [
        migrations.RunPython(setup_roles_and_permissions),
    ]
